/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.PecasBean;
import model.PecasDAO;

/**
 *
 * @author Aluno
 */
public class Cadastropeca extends javax.swing.JFrame {

    private int idSelecionado = 0;
    /**
     * Creates new form Cadastropeca
     */
    public Cadastropeca() {
        initComponents();
    }

    public void carregarParaEdicao(int id) {

    idSelecionado = id;

    PecasDAO dao = new PecasDAO();
    PecasBean novaPeca = dao.buscarPorId(id);

    nomePeca.setText(novaPeca.getNome());
    tipoPeca.setText(novaPeca.getTipo());
    compatibilidadePeca.setText(novaPeca.getCompatibilidade());
    codigoPeca.setText(novaPeca.getCodigo_fabricante());
    quantidadePeca.setText(String.valueOf(novaPeca.getQuantidade_estoque()));
    precoPeca.setText(String.valueOf(novaPeca.getPreco()));
    fornecedorPeca.setText(novaPeca.getFornecedor());
    descricaoPeca.setText(novaPeca.getDescricao());
    materialPeca.setSelectedItem(novaPeca.getMaterial());
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTiuloCadastro = new javax.swing.JLabel();
        nomePeca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        quantidadePeca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigoPeca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaoAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tipoPeca = new javax.swing.JTextField();
        precoPeca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        compatibilidadePeca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fornecedorPeca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        descricaoPeca = new javax.swing.JTextField();
        materialPeca = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Peças");

        nomeTiuloCadastro.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        nomeTiuloCadastro.setText("CADASTRAR PEÇAS");
        nomeTiuloCadastro.setPreferredSize(new java.awt.Dimension(385, 31));

        nomePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePecaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        quantidadePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadePecaActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        codigoPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPecaActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo");

        botaoAdicionar.setText("ADICIONAR");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo");

        precoPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoPecaActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço");

        jLabel6.setText("Compatiblidade");

        jLabel7.setText("Fornecedor");

        jLabel8.setText("Material");

        jLabel9.setText("Descrição");

        materialPeca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Borracha", "Aço", "Plástico", "Universal" }));
        materialPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialPecaActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePeca, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(codigoPeca)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(22, 22, 22))
                                            .addComponent(quantidadePeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(tipoPeca)
                                    .addComponent(jLabel5)
                                    .addComponent(precoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(fornecedorPeca)
                                    .addComponent(compatibilidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descricaoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(materialPeca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(nomeTiuloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(nomeTiuloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compatibilidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePecaActionPerformed

    private void codigoPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoPecaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio ();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        // TODO add your handling code here:
       if (nomePeca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo NOME não foi preenchido", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        else if (materialPeca.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo MATERIAL não foi preenchido", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        else if (quantidadePeca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo QTD não foi preenchido", "Erro", JOptionPane.WARNING_MESSAGE);
        }   
        else if (precoPeca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo PREÇO não foi preenchido", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        else {

       PecasBean novaPeca = new PecasBean();

            novaPeca.setNome(nomePeca.getText());
            novaPeca.setTipo(tipoPeca.getText());
            novaPeca.setCompatibilidade(compatibilidadePeca.getText());
            novaPeca.setCodigo_fabricante(codigoPeca.getText());
            novaPeca.setQuantidade_estoque(Integer.parseInt(quantidadePeca.getText()));
            novaPeca.setPreco(Double.parseDouble(precoPeca.getText()));
            novaPeca.setFornecedor(fornecedorPeca.getText());
            novaPeca.setDescricao(descricaoPeca.getText());
            novaPeca.setMaterial(materialPeca.getSelectedItem().toString());

            PecasDAO dao = new PecasDAO();
            dao.inserirPeca(novaPeca);

            JOptionPane.showMessageDialog(null, "Nova Peça cadastrada", "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);

            Inicio inicio = new Inicio();
            inicio.setVisible(true);
            this.dispose();
}
        
//        Inicio inicio = new Inicio ();
//        inicio.setVisible(true);
        
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void quantidadePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadePecaActionPerformed

    private void materialPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialPecaActionPerformed

    private void precoPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoPecaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    PecasBean novaPeca = new PecasBean();

        novaPeca.setNome(nomePeca.getText());
        novaPeca.setTipo(tipoPeca.getText());
        novaPeca.setCompatibilidade(compatibilidadePeca.getText());
        novaPeca.setCodigo_fabricante(codigoPeca.getText());
        novaPeca.setQuantidade_estoque(Integer.parseInt(quantidadePeca.getText()));

        String valor = precoPeca.getText().replace(",", ".");
        novaPeca.setPreco(Double.parseDouble(valor));

        novaPeca.setFornecedor(fornecedorPeca.getText());
        novaPeca.setDescricao(descricaoPeca.getText());
        novaPeca.setMaterial(materialPeca.getSelectedItem().toString());

        PecasDAO dao = new PecasDAO();

   
        if (idSelecionado != 0) {

            novaPeca.setId_pecas(idSelecionado); // 
            dao.atualizar(novaPeca);

            JOptionPane.showMessageDialog(this, "Peça atualizada!");

        }  
        else {

        dao.inserirPeca(novaPeca);
            
            this.dispose();
        JOptionPane.showMessageDialog(this, "Peça cadastrada!");
    }
        Inicio inicio = new Inicio ();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastropeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastropeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastropeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastropeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastropeca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField codigoPeca;
    private javax.swing.JTextField compatibilidadePeca;
    private javax.swing.JTextField descricaoPeca;
    private javax.swing.JTextField fornecedorPeca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> materialPeca;
    private javax.swing.JTextField nomePeca;
    private javax.swing.JLabel nomeTiuloCadastro;
    private javax.swing.JTextField precoPeca;
    private javax.swing.JTextField quantidadePeca;
    private javax.swing.JTextField tipoPeca;
    // End of variables declaration//GEN-END:variables
}
