/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PecasBean;
import model.PecasDAO;

/**
 *
 * @author Aluno
 */
public class Inicio extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form Inicio
     */
     public Inicio() {
        initComponents();
        preencherTabela();
    }

    public void preencherTabela() {
        model = (DefaultTableModel) tablePecas.getModel();
        model.setRowCount(0);
        
       PecasDAO dao = new PecasDAO();
       List<PecasBean> pecas = dao.ler();

        for(PecasBean prod: pecas) {
            Object[] linha = {
                prod.getId_pecas(),
                prod.getNome(),
                prod.getDescricao(),
                prod.getCodigo_fabricante(),
                prod.getTipo(),
                prod.getMaterial(),
                prod.getCompatibilidade(),
                prod.getQuantidade_estoque(),
                prod.getPreco(),
                prod.getFornecedor()
            };
            
            model.addRow(linha);
        }
    }
        
    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePecas = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        tablePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Codigo_fabricante", "Tipo", "Material", "Compatibilidade", "Quantidade_estoque", "Preço", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePecas.setToolTipText("");
        jScrollPane1.setViewportView(tablePecas);
        if (tablePecas.getColumnModel().getColumnCount() > 0) {
            tablePecas.getColumnModel().getColumn(0).setResizable(false);
        }

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton2.setText("CADASTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMais.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMais.setText("+");
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355)
                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMais))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
       int selectedRow = tablePecas.getSelectedRow();

       if (selectedRow == -1) {
       JOptionPane.showMessageDialog(this, "Selecione uma peça");
       return;
       }

       int id = Integer.parseInt(tablePecas.getValueAt(selectedRow, 0).toString());

       Cadastropeca cadastropeca = new Cadastropeca ();
       cadastropeca.setVisible(true);
       cadastropeca.carregarParaEdicao(id);
       this.dispose();
       
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cadastropeca cadastropeca = new Cadastropeca ();
        cadastropeca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        int selectedRow = tablePecas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma PEÇA para exluir", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int pecaId = (int) tablePecas.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Exluir PEÇA?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            
            PecasDAO dao = new PecasDAO();
            dao.deletar(pecaId);
            JOptionPane.showMessageDialog(this, "Peça deletada", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            preencherTabela();
        }
        
        Inicio inicio = new Inicio ();
        inicio.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        // TODO add your handling code here:
        
            int linha = tablePecas.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma peça!");
        return;
    }

        try {
            int id = Integer.parseInt(tablePecas.getValueAt(linha, 0).toString());
            int quantidade = Integer.parseInt(tablePecas.getValueAt(linha, 7).toString());

           int novaQuantidade = quantidade + 1;

        PecasDAO dao = new PecasDAO();
        dao.atualizarQuantidade(id, novaQuantidade);

       // Atualiza na tabela
        preencherTabela();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao atualizar quantidade!");
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:  
        
        int linha = tablePecas.getSelectedRow();

    if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma peça!");
        return;
    }

    try {
        int id = Integer.parseInt(tablePecas.getValueAt(linha, 0).toString());
        int quantidade = Integer.parseInt(tablePecas.getValueAt(linha, 7).toString());

        if (quantidade <= 0) {
                JOptionPane.showMessageDialog(null, "Estoque já está zerado!");
            return;
        }

        int novaQuantidade = quantidade - 1;

        PecasDAO dao = new PecasDAO();
        dao.atualizarQuantidade(id, novaQuantidade);

        // Atualiza na tabela
        preencherTabela();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao atualizar quantidade!");
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePecas;
    // End of variables declaration//GEN-END:variables
}
    
